- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup
    - name: Import VPC Variables
      include_vars: vars/vpc-output_vars

    - name: Delete nat gateway 
      ec2_vpc_nat_gateway:
        state: absent
        region: "{{region}}"
        wait: true
        nat_gateway_id: "{{ NATGWid }}"
        release_eip: true
        wait_timeout: 500
      register: delete_nat_gateway_result


    - name: Internet Gateway Delete
      ec2_vpc_igw:
        vpc_id: "{{vpcid}}"
        region: "{{region}}"
        state: absent
        resource_tags:
          Name: vprofile_IGW
      register: igw_out

    - name: Remove subnets 
      ec2_vpc_subnet:
        state: absent
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        cidr: 
          - "{{ PrivSub1Cidr }}"
          - "{{ PrivSub2Cidr }}"
          - "{{ PubSub1Cidr }}"
          - "{{ PubSub2Cidr }}"

    - name: Set down public subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{vpcid}}"
        region: "{{ region }}"
        route_table_id: "{{item}}"
        lookup: id
      loop:
        - "{{privRTid}}"
        - "{{pubRTid}}"


    - name: Delete vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        state: absent
      register: vpcout

- "{{pubsub1id}}"
- "{{pubsub2id}}"
- "{{privsub1id}}"
- "{{privsub2id}}"

# region: us-east-1
# vpcid: vpc-05de7c5d0d740b905
# pubsub1id: subnet-05572f9ee91a55306
# pubsub2id: subnet-0f73a4df49466a37f
# privsub1id: subnet-01957efaa884403db
# privsub2id: subnet-0866567fca58349df
# igwid: igw-064c12b532b3a96d1
# pubRTid: rtb-0f2d8cf55ddeae8da
# NATGWid: nat-0f4247dabe6446a56
# privRTid: rtb-032325d9fbff6b8db